[project]
name = "data-accessor"
version = "0.1.0"
description = "Data access solution"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "asyncpg>=0.30.0",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "sqlalchemy[asyncio]>=2.0.42",
    "toml>=0.10.2",
    "toml-cli>=0.8.1",
]

[project.scripts]
data-accessor = "data_accessor:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/data_accessor"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
